networks:
  default: development
compiler:
  solc:
    remappings:
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.2.0/contracts"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0/contracts"
      - "@gnosis.pm/safe-contracts=safe-global/safe-contracts@1.3.0"
